### ISSUE TITLE
No module name 'requests'.

### ISSUE THREAD

**Issue by DankoLobosB** [pyhackertarget/hackertarget#5]
When I try to execute in my terminal (Ubuntu 18.04):

`python hackertarget.py`

It returns an Import error:

`ImportError: No module named requests`

Tried to find the module but I couldn't, even I couldn't find it in the repository.

Please help, thanks.

**Comment by ismailtasdelen** [comment]
Thanks for the suggestion. We have prepared the requirements.txt file. You can install missing packages with the pip install -r requirements.txt command.

**Comment by ismailtasdelen** [comment]
https://github.com/pyhackertarget/hackertarget/blob/master/requirements.txt
