### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by peter279k** [pyhackertarget/hackertarget#7]
As title. I think we should consider versioning the this Python script version.

We can use the `git tag` to release stable version.

@ismailtasdelen, do you have any idea about this?

**Comment by ismailtasdelen** [comment]
@peter279k I'm gonna go back to you for this.

**Comment by ismailtasdelen** [comment]
Hi @peter279k ,

The stable version I created below must have solved the problem.

https://github.com/pyhackertarget/hackertarget/releases/tag/v1.2.3

Thanks feedback !

**Comment by peter279k** [comment]
Closed.
